/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RyuBeian: typeof import('./src/components/ryu-beian.vue')['default']
    RyuCode: typeof import('./src/components/ryu-code.vue')['default']
    RyuSvg: typeof import('./src/components/ryu-svg.vue')['default']
    WtuAvatar: typeof import('./src/components/wtu-avatar.vue')['default']
    WtuBooster: typeof import('./src/components/wtu-booster.vue')['default']
    WtuEntries: typeof import('./src/components/wtu-entries.vue')['default']
    WtuFooter: typeof import('./src/components/wtu-footer.vue')['default']
    WtuHeader: typeof import('./src/components/wtu-header.vue')['default']
    WtuLogo: typeof import('./src/components/wtu-logo.vue')['default']
  }
}
