/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RyuBeian: typeof import('./src/components/ryu-beian.vue')['default']
    RyuCode: typeof import('./src/components/ryu-code.vue')['default']
    RyuSponsor: typeof import('./src/components/ryu-sponsor.vue')['default']
    RyuSvg: typeof import('./src/components/ryu-svg.vue')['default']
    WtuActivity: typeof import('./src/components/wtu-activity.vue')['default']
    WtuAppname: typeof import('./src/components/wtu-appname.vue')['default']
    WtuAvatar: typeof import('./src/components/wtu-avatar.vue')['default']
    WtuBooster: typeof import('./src/components/wtu-booster.vue')['default']
    WtuBreadcrumb: typeof import('./src/components/wtu-breadcrumb.vue')['default']
    WtuDifficulty: typeof import('./src/components/wtu-difficulty.vue')['default']
    WtuEntries: typeof import('./src/components/wtu-entries.vue')['default']
    WtuFocus: typeof import('./src/components/wtu-focus.vue')['default']
    WtuFocusList: typeof import('./src/components/wtu-focus-list.vue')['default']
    WtuFooter: typeof import('./src/components/wtu-footer.vue')['default']
    WtuHeader: typeof import('./src/components/wtu-header.vue')['default']
    WtuLoadout: typeof import('./src/components/wtu-loadout.vue')['default']
    WtuLogo: typeof import('./src/components/wtu-logo.vue')['default']
    WtuOnlineState: typeof import('./src/components/wtu-online-state.vue')['default']
    WtuProfileRoute: typeof import('./src/components/wtu-profile-route.vue')['default']
    WtuServer: typeof import('./src/components/wtu-server.vue')['default']
    WtuTeamSet: typeof import('./src/components/wtu-team-set.vue')['default']
    WtuWarframe: typeof import('./src/components/wtu-warframe.vue')['default']
    WtuWarframeList: typeof import('./src/components/wtu-warframe-list.vue')['default']
  }
}
