/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AccountHeader: typeof import('./src/components/account-header.vue')['default']
    Avatar: typeof import('./src/components/avatar/avatar.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    IconMoon: typeof import('./src/components/pubs/icon-moon.vue')['default']
    IconNight: typeof import('./src/components/pubs/icon-night.vue')['default']
    IconSun: typeof import('./src/components/pubs/icon-sun.vue')['default']
    Moon: typeof import('./src/components/moon.vue')['default']
    Pubs: typeof import('./src/components/pubs/pubs.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RyuBeian: typeof import('./src/components/ryu-beian.vue')['default']
    RyuHeader: typeof import('./src/components/ryu-header.vue')['default']
    RyuLogo: typeof import('./src/components/ryu-logo.vue')['default']
    RyuSvg: typeof import('./src/components/ryu-svg.vue')['default']
    WtuAvatar: typeof import('./src/components/wtu-avatar.vue')['default']
    WtuEntries: typeof import('./src/components/wtu-entries.vue')['default']
    WtuFooter: typeof import('./src/components/wtu-footer.vue')['default']
    WtuHeader: typeof import('./src/components/wtu-header.vue')['default']
    WtuLogo: typeof import('./src/components/wtu-logo.vue')['default']
  }
}
